export const FILTERS = [
  { id: "all", label: "All" },
  { id: "marketing", label: "Marketing" },
  { id: "management", label: "Management" },
  { id: "hr", label: "HR & Recruiting" },
  { id: "design", label: "Design" },
  { id: "development", label: "Development" },
];

export const coursesData = [
  {
    id: 1,
    title: "The Ultimate Google Ads Training Course",
    category: "marketing",
    badgeText: "Marketing",
    badgeTheme: "marketing",
    price: "$100",
    author: "| by Jerome Bell",
    image: "img/course-1.png",
  },
  {
    id: 2,
    title: "Product Management Fundamentals",
    category: "management",
    badgeText: "Management",
    badgeTheme: "management",
    price: "$480",
    author: "| by Marvin McKinney",
    image: "img/course-2.png",
  },
  {
    id: 3,
    title: "HR Management and Analytics",
    category: "hr",
    badgeText: "HR & Recruiting",
    badgeTheme: "hr",
    price: "$200",
    author: "| by Leslie Alexander Li",
    image: "img/course-3.png",
  },
  {
    id: 4,
    title: "Brand Management & PR Communications",
    category: "marketing",
    badgeText: "Marketing",
    badgeTheme: "marketing",
    price: "$530",
    author: "| by Kristin Watson",
    image: "img/course-4.png",
  },
  {
    id: 5,
    title: "Graphic Design Basic",
    category: "design",
    badgeText: "Design",
    badgeTheme: "design",
    price: "$500",
    author: "| by Guy Hawkins",
    image: "img/course-5.png",
  },
  {
    id: 6,
    title: "Business Development Management",
    category: "management",
    badgeText: "Management",
    badgeTheme: "management",
    price: "$400",
    author: "| by Dianne Russell",
    image: "img/course-6.png",
  },
  {
    id: 7,
    title: "Highload Software Architecture",
    category: "development",
    badgeText: "Development",
    badgeTheme: "development",
    price: "$600",
    author: "| by Brooklyn Simmons",
    image: "img/course-7.png",
  },
  {
    id: 8,
    title: "Human Resources – Selection and Recruitment",
    category: "hr",
    badgeText: "HR & Recruiting",
    badgeTheme: "hr",
    price: "$150",
    author: "| by Kathryn Murphy",
    image: "img/course-8.png",
  },
  {
    id: 9,
    title: "User Experience. Human-centered Design",
    category: "design",
    badgeText: "Design",
    badgeTheme: "design",
    price: "$240",
    author: "| by Cody Fisher",
    image: "img/course-9.png",
  },
  {
    id: 10,
    title: "Digital Marketing Strategy Intensive",
    category: "marketing",
    badgeText: "Marketing",
    badgeTheme: "marketing",
    price: "$350",
    author: "| by Jerome Bell",
    image: "img/course-1.png",
  },
  {
    id: 11,
    title: "Social Media Campaigns from Scratch",
    category: "marketing",
    badgeText: "Marketing",
    badgeTheme: "marketing",
    price: "$290",
    author: "| by Kristin Watson",
    image: "img/course-4.png",
  },
  {
    id: 12,
    title: "Agile Product Leadership",
    category: "management",
    badgeText: "Management",
    badgeTheme: "management",
    price: "$450",
    author: "| by Dianne Russell",
    image: "img/course-6.png",
  },
  {
    id: 13,
    title: "HR Metrics and Reporting",
    category: "hr",
    badgeText: "HR & Recruiting",
    badgeTheme: "hr",
    price: "$220",
    author: "| by Leslie Alexander Li",
    image: "img/course-3.png",
  },
  {
    id: 14,
    title: "Talent Acquisition Essentials",
    category: "hr",
    badgeText: "HR & Recruiting",
    badgeTheme: "hr",
    price: "$180",
    author: "| by Kathryn Murphy",
    image: "img/course-8.png",
  },
  {
    id: 15,
    title: "Employee Engagement Programs",
    category: "hr",
    badgeText: "HR & Recruiting",
    badgeTheme: "hr",
    price: "$260",
    author: "| by Leslie Alexander Li",
    image: "img/course-3.png",
  },
  {
    id: 16,
    title: "Scalable Backend Systems",
    category: "development",
    badgeText: "Development",
    badgeTheme: "development",
    price: "$650",
    author: "| by Brooklyn Simmons",
    image: "img/course-7.png",
  },
  {
    id: 17,
    title: "Cloud-native Architecture in Practice",
    category: "development",
    badgeText: "Development",
    badgeTheme: "development",
    price: "$680",
    author: "| by Brooklyn Simmons",
    image: "img/course-7.png",
  },
];
